### ISSUE TITLE
Which IDEs are supperted? Is PyCharm supported?

### ISSUE THREAD

**Issue by Ashark** [alex1701c/JetBrainsDolphinPlugin#1]
I am on Arch Linux. I have cloned this repo and installed plugin with `install-user.sh` script.

In Dolphin when I right click at folder with python project, in the menu there is no any item regarding jetbrains ides. The folder contains a subfolder ".idea" and the project files. The project was developed in PyCharm community edition IDE, so pycharm should "know" about that project path.

What am I doing wrong? Was this service menu tested against pycharm project folders?
Or maybe I should start some service which listens jetbrains api requests that or something like that?

Also, strange that when I right click on empty space in the folder which is not a project folder, I see a top menu entry "Jetbrains" but it does not contain any sub items. Probably this is not intended behavior.

**Comment by Ashark** [comment]
Looks like just running `pycharm %u` in the project folder (that contains .idea subfolder) opens the project normally. Is there a specific reason to use api which is not working? Installed ides can be easily checked by just checking their binaries existance. Probably for checking to which ide the project belongs?

**Comment by gmm96** [comment]
I also suffered the same bug, no Pycharm community entry appears in this menu.
What it is weird, I have installed Intellij Proffesional version and it does appear, but it seems no community version will appear.
 I have installed the plugin using _Dolphin store_ and Pycharm/Intellij using AUR.

**Comment by alex1701c** [comment]
Thanks for reporting this bug, I will look into it.

**Comment by alex1701c** [comment]
It is caused by some filenames being inconsistent. I will rewrite the search code to be more robust, the KDE frameworks have great functionality for this which I am already familiar with.

**Comment by alex1701c** [comment]
Could you please update the src/jetbrains-api submodule and check out the `work/parsing` branch of this repo?

If you confirm the fix I will merge the changes to master

**Comment by Ashark** [comment]
The behavior is the same. In non-project folders there is a top level menu entry Jetbrains with no items in it. And in the project folders (that contains .idea subfolder) there is no Jetbrains menu entry.

**Comment by alex1701c** [comment]
Could you pleas do a `git log` in the `src/jetbrains-api/` dir? Then a commit with the title "Use KApplicationTrader to make search more robust" should show up. If not please pull.

Could you please upload your desktop file from the application?

**Comment by Ashark** [comment]
For some reason, in `src/jetbrains-api/` dir the `git status` said that the HEAD was "detached". I did `git checkout master`, then `git pull` and now I see that "Use KApplicationTrader..." commit and the following "Add .gitignore file" (8e5ca9) commit.

Now I run `install-user.sh` again. And still no effect, like in my previous comment.

Additional info (I do not know if that is important): in Dolphin the src subfolder is marked as changed and the status in the main module is `modified:   src/jetbrains-api (new commits)`

> Could you please upload your desktop file from the application?

You mean my ~/.local/share/kservices5/jetbrainsdolphinplugin.desktop? Here it is:
```
[Desktop Entry]
Type=Service
Name=JetBrainsDolphinPlugin
Icon=jetbrains
X-KDE-ServiceTypes=KFileItemAction/Plugin
MimeType=inode/directory
X-KDE-Library=jetbrainsdolphinplugin
```

**Comment by alex1701c** [comment]
The one from the jetbrains app, there are multiple in the AUR and I am not 100% sure which one I should test.
Thanks :)

**Comment by Ashark** [comment]
I am using an official package from archlinux: pycharm-community-edition 2021.1.3-1
Here is its desktop file:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm Community Edition
Comment=Python IDE for Professional Developers
Exec=/usr/bin/pycharm %f
Icon=pycharm
Terminal=false
StartupNotify=true
StartupWMClass=jetbrains-pycharm-ce
Categories=Development;IDE;Python;
```

**Comment by alex1701c** [comment]
That is weird, when I out the text you pasted in ~/.local/share/applications/testme.desktop and change the name to sth. different (so I can differentiate it) it shows up.

You used the install-user.sh script? Could you please source the `prefix.sh` script that is created in the build dir. Maybe the updated build is not loaded...

PS: The `StartupWMClass=jetbrains-pycharm-ce` line is exactly what https://github.com/alex1701c/jetbrains-api/blob/master/JetbrainsApplication.cpp#L126 should catch

**Comment by Ashark** [comment]
> Could you please source the prefix.sh script that is created in the build dir.

What do you mean under "source"? Do you mean I need to run `source build/prefix.sh` before running `./install-user.sh`? I did that, reported that successfully built and installed, but still no effect. Also I checked by restarting Dolphin to be sure.

Or you mean just show its content? Here it is:
```
export PATH=/usr/bin:$PATH

# LD_LIBRARY_PATH only needed if you are building without rpath
# export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH

export XDG_DATA_DIRS=/usr/share:${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}
export XDG_CONFIG_DIRS=/etc/xdg:${XDG_CONFIG_DIRS:-/etc/xdg}

export QT_PLUGIN_PATH=~/.local/lib/qt/plugins:$QT_PLUGIN_PATH
export QML2_IMPORT_PATH=/usr/lib/qt/qml:$QML2_IMPORT_PATH

export QT_QUICK_CONTROLS_STYLE_PATH=/usr/lib/qt/qml/QtQuick/Controls.2/:$QT_QUICK_CONTROLS_STYLE_PATH
```

**Comment by alex1701c** [comment]
Hmm, does changing the text in src/jetbrainsdolphinplugin.cpp:78 and src/jetbrainsdolphinplugin.cpp:114 change the text of the empty "Jetbrains" menu entry?

Also what does `ktraderclient5 --servicetype Application --constraint "'jetbrains-pycharm-ce'  ~~ StartupWMClass"` output on your system?

**Comment by Ashark** [comment]
According to line numbers you say, you are now talking again about master branch. I tried both with master and with work/parsing branches. I changed them to different values like `QStringLiteral("Jetbrains&&&")`. Then run install-user.sh successfully and restarted dolphin. And **no**, the empty menu entry in non-project folders is still named "Jetbrains".

Here is the output of the command:
```
$ ktraderclient5 --servicetype Application --constraint "'jetbrains-pycharm-ce' ~~ StartupWMClass"
servicetype is : Application
constraint is : 'jetbrains-pycharm-ce' ~~ StartupWMClass
got 1 offers.
---- Offer 0 ----
StartupNotify : 'TRUE'
StartupWMClass : 'jetbrains-pycharm-ce'
Type : 'Application'
Name : 'PyCharm Community Edition'
Comment : 'Python IDE for Professional Developers'
Invalid property GenericName
Icon : 'pycharm'
Exec : '/usr/bin/pycharm %f'
Terminal : 'FALSE'
Invalid property TerminalOptions
Invalid property Path
ServiceTypes : 'Application'
AllowAsDefault : 'TRUE'
InitialPreference : '1'
Invalid property Library
DesktopEntryPath : '/usr/share/applications/pycharm.desktop'
DesktopEntryName : 'pycharm'
Keywords : ''
FormFactors : ''
Categories : 'Development - IDE - Python'
```

**Comment by alex1701c** [comment]
Could you please try removing the old files in case they are lying around on disk:

```
rm ~/.local/lib/qt/plugins/jetbrainsdolphinplugin.so
sudo rm /usr/lib/x86_64-linux-gnu/qt5/plugins/jetbrainsdolphinplugin.so
```

If all goes well you should not have any entry at all. Can you try the `install.sh` script after that?

>Here is the output of the command:

Thanks, the output looks good!

**Comment by Ashark** [comment]
Wow, it worked now. I had no /usr/lib/x86_64-linux-gnu/qt5/plugins/jetbrainsdolphinplugin.so, but had ~/.local/lib/qt/plugins/jetbrainsdolphinplugin.so. I removed it, then `install.sh`.
I restarted dolphin, and now I can see the these menus.

**Comment by alex1701c** [comment]
Cool, so everything works properly now?

**Comment by Ashark** [comment]
Yes, working properly, including that there is no empty entry in menu that I mentioned in comment 1.
I deleted files that I do not remember how they were installed (I sugest adding uninstallation instructions):
/usr/share/pixmaps/jetbrains.png
/usr/share/kservices5/jetbrainsdolphinplugin.desktop

You can now publish it to store.kde.org.

**Comment by alex1701c** [comment]
> I deleted files that I do not remember how they were installed (I sugest adding uninstallation instructions):

Okay, will do

Out of interest, what is your KDE frameworks version?

**Comment by Ashark** [comment]
Thanks.
> what is your KDE frameworks version?

5.86.0

**Comment by alex1701c** [comment]
Okay, I will need to do some minor porting for the plugin system.

After that and with https://invent.kde.org/frameworks/kio/-/commit/42664c0a408e38a6d6a992756288e972a3f80900 the explicit uninstall is not needed anymore :)
