### ISSUE TITLE
Enable support for Plasma 6

### ISSUE THREAD

**Issue by Ashark** [alex1701c/JetBrainsDolphinPlugin#10]
Request similar to [this](https://github.com/alex1701c/JetBrainsRunner/issues/42).

I have tried to build with this command: 
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_QT6=ON ..
```
But it still installed to "/usr/lib/qt/plugins/kf**5**/kfileitemaction/jetbrainsdolphinplugin.so" and "/usr/share/qlogging-categories**5**/jetbrainsservicemenu.categories"

Also, I see this warning in the output:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_WITH_QT6
```

**Comment by alex1701c** [comment]
I don't have any local patch this time, but the effort should be reasonable :)

**Comment by Ashark** [comment]
Cool! Thanks!
Now, I have successfully built it, but when installing, I see it has the conflicting file with jetbrains-runner:

```
error: failed to commit transaction (conflicting files)
kf6-servicemenus-jetbrains-dolphin-plugin-git: /usr/share/qlogging-categories6/jetbrains-api.categories exists in filesystem (owned by plasma6-runners-jetbrains-runner-git)
```
Can we make them so they do not conflict?

**Comment by alex1701c** [comment]
Oh, I see. That file is from the core library, but installed for both.

**Comment by Ashark** [comment]
I have uploaded plasma 6 version to aur: https://aur.archlinux.org/packages/kf6-servicemenus-jetbrains-dolphin-plugin-git
You can also add it to Readme.

**Comment by Ashark** [comment]
> Oh, I see. That file is from the core library, but installed for both.

So maybe it should be installed as a separate package instead?

**Comment by Ashark** [comment]
Oh, I see, you already removed `/usr/share/qlogging-categories6/jetbrains-api.categories`  file from JetBrainsDolphinPlugin. But it is still in JetBrainsRunner.

Does that will mean that for `kf6-servicemenus-jetbrains-dolphin-plugin-git` I should add `plasma6-runners-jetbrains-runner-git` to depends list?
