### ISSUE TITLE
install  error

### ISSUE THREAD

**Issue by yinxiulong** [alex1701c/JetBrainsDolphinPlugin#2]
![image](https://user-images.githubusercontent.com/26619335/123022012-b024e680-d407-11eb-9177-b30c7c50a423.png)

**Comment by Ashark** [comment]
I also had installation error. But I had installed it manually as described in readme.
I recommend to edit your report by attaching a screenshot with English language and describing your software, such as distribution, application versions and so on.

**Comment by alex1701c** [comment]
Can you search for packagekit-qt5 and check if it is installed? I think on arch was some trouble with that (caused by the packaging of dolphin)

**Comment by alex1701c** [comment]
https://bugs.archlinux.org/task/71522 Seems like arch packagers expect you to fix the issue on your own. That has nothing to do with this plugin specifically.
