### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Ashark** [alex1701c/JetBrainsDolphinPlugin#8]
Hello.
I am packaging this plugin for Arch Linux. Please specify the license.

**Comment by alex1701c** [comment]
Thanks for packaging. I have added a license file.

**Comment by Ashark** [comment]
Thanks for this awesome plugin!

Can you also fix this:
```
CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by Ashark** [comment]
Uploaded Arch Linux AUR package. Can you please mention the [kf5-servicemenus-jetbrains-dolphin-plugin-git](https://aur.archlinux.org/packages/kf5-servicemenus-jetbrains-dolphin-plugin-git) in Readme, and in the strore.kde.org description?

**Comment by alex1701c** [comment]
I have added this to the readme last week :)

**Comment by Ashark** [comment]
That was for runner plugin: https://github.com/alex1701c/JetBrainsRunner/issues/40

**Comment by alex1701c** [comment]
Done
