### ISSUE TITLE
Unwanted "%f" window opens

### ISSUE THREAD

**Issue by Ashark** [alex1701c/JetBrainsDolphinPlugin#9]
For some reason, when invoking the ide by this Dolphin plugin, the IDE opens the window called "%f" in addition to the window with the project.
When I call the IDE from terminal, like `idea-ce-eap /home/username/path/to/project/dir`, the IDE opens just the window with the project.
Can this be fixed?

**Comment by alex1701c** [comment]
Yeah, I should utilize the KIO DesktopExecParser to avoid %f, %F or similar placeholder issues

**Comment by Ashark** [comment]
Very waiting :)

**Comment by Ashark** [comment]
Thanks for update. Now, when opening not yet existing project, it asks if I want to trust the project.
But the path to the project became "temporary" (somewhere inside `/run/user...`)?

![Path to project is not real](https://github.com/alex1701c/JetBrainsDolphinPlugin/assets/22634975/af98c827-17b9-4193-b4ac-e602859177c6)

Is that related to update?

**Comment by alex1701c** [comment]
>But the path to the project became "temporary" (somewhere inside /run/user...)?

That might be due to kio-fuse. Do you have it on a network mount somewhere?

**Comment by Ashark** [comment]
No, my projects are located in local filesystem, in this case, the path to the project is: `/home/andrew/kde6/src/kiconthemes/`. And previously, that window showed the normal path (without fuse).

**Comment by alex1701c** [comment]
That is weird. Maybe the implicit URL conversion causes issues. I'll need to look into the KF5 DesktopExecParser code to see what is going on there ^^

**Comment by alex1701c** [comment]
Could you please try again with latest master?

**Comment by Ashark** [comment]
Yeah, you fixed that!
Now it asks the correct path (not fused) [of course, it you did not marked folder as trusted previously].
Also, the problem of "%u" empty window  does not appear.
Thank you!
